packages:
  - 'packages/**'
  - 'sdk/**'
  - 'apps/**'

catalog:
  # Fastify
  'fastify': '^5.1.0'
  'fastify-plugin': '^5.0.1'
  '@fastify/cors': '^10.0.1'
  '@fastify/swagger': '^9.4.0'

  # Node / TypeScript
  '@types/node': '^22.10.6'
  'tsx': '^4.19.2'
  'typescript': '^5.8.3'

  # React
  'react': '19.2.2'
  'react-dom': '19.2.2'
  '@types/react': '19.2.2'
  '@types/react-dom': '19.2.2'

  # Libs
  'zod': '^3.24.2'
  'axios': '^1.8.3'
  '@tanstack/react-query': '^5.74.4'
  'orval': '7.4.0'
  'lucide-react': '^0.477.0'
  'tailwindcss': '^3.4.4'
  'postcss': '^8.4.38'
  'autoprefixer': '^10.4.19'
